export const BANK_SELECT = 'BANK_SELECT';

export const RECEIVE_TRANSACTIONS = 'RECEIVE_TRANSACTIONS';

export const REQUEST_TRANSACTIONS = 'REQUEST_TRANSACTIONS';

export const LOGIN_FORM_UPDATE = 'LOGIN_FORM_UPDATE';

export const LOGIN_FORM_VALIDATE = 'LOGIN_FORM_VALIDATE';

export const LOGIN = 'LOGIN';

export const LOGOUT = 'LOGOUT';
